import taskListImage from "@/assets/task-list-feature.jpg";
import codeDiffImage from "@/assets/code-diff-feature.jpg";
import mcpImage from "@/assets/mcp-feature.jpg";

const DetailedFeatures = () => {
  return (
    <section className="py-20 bg-gradient-to-b from-background to-background/50">
      <div className="container mx-auto px-6">
        <div className="max-w-6xl mx-auto">
          {/* Section Header */}
          <div className="text-center mb-20">
            <h2 className="text-4xl md:text-5xl font-bold text-foreground mb-6">
              Go from <span className="bg-gradient-hero bg-clip-text text-transparent">vibe coding</span> to <span className="bg-gradient-hero bg-clip-text text-transparent">viable code</span>
            </h2>
          </div>

          {/* Feature 1 - Spec-driven development */}
          <div className="grid lg:grid-cols-2 gap-12 items-center mb-20">
            <div>
              <h3 className="text-3xl font-bold text-foreground mb-6">
                Bring structure to AI coding with spec-driven development
              </h3>
              <p className="text-lg text-muted-foreground leading-relaxed mb-6">
                Kiro turns your prompt into clear requirements, structured designs, implementation tasks validated by robust tests, and code generated by advanced agents. It's the flow of AI coding, leveled up with <a href="#" className="text-primary hover:text-primary/80 underline">mature engineering practices</a>.
              </p>
            </div>
            <div className="relative">
              <div className="bg-gradient-primary p-1 rounded-2xl">
                <img 
                  src={taskListImage} 
                  alt="Kiro's task list with complete and pending tasks"
                  className="w-full rounded-2xl"
                />
              </div>
            </div>
          </div>

          {/* Feature 2 - Built for agents */}
          <div className="grid lg:grid-cols-2 gap-12 items-center mb-20">
            <div className="lg:order-2">
              <h3 className="text-3xl font-bold text-foreground mb-6">
                Built from the ground-up for working with agents
              </h3>
              <p className="text-lg text-muted-foreground leading-relaxed mb-6">
                <a href="#" className="text-primary hover:text-primary/80 underline">Multimodal chat</a>, <a href="#" className="text-primary hover:text-primary/80 underline">spec-driven development</a>, <a href="#" className="text-primary hover:text-primary/80 underline">agent hooks</a> - Kiro gives you the best tool for the job in a fresh development experience that still feels familiar.
              </p>
            </div>
            <div className="lg:order-1 relative">
              <div className="bg-gradient-primary p-1 rounded-2xl">
                <img 
                  src={codeDiffImage} 
                  alt="Kiro shows code diff view with chat for building features"
                  className="w-full rounded-2xl"
                />
              </div>
            </div>
          </div>

          {/* Feature 3 - More context */}
          <div className="grid lg:grid-cols-2 gap-12 items-center mb-20">
            <div>
              <h3 className="text-3xl font-bold text-foreground mb-6">
                More context, less repetition
              </h3>
              <p className="text-lg text-muted-foreground leading-relaxed mb-6">
                With specs, <a href="#" className="text-primary hover:text-primary/80 underline">steering</a>, and smart context management, Kiro understands the intent behind your prompts and helps you implement complex features on larger codebases, in fewer shots.
              </p>
            </div>
            <div className="relative">
              <div className="bg-gradient-primary p-1 rounded-2xl">
                <img 
                  src={codeDiffImage} 
                  alt="Kiro reads files and displays tools for exploring code"
                  className="w-full rounded-2xl"
                />
              </div>
            </div>
          </div>

          {/* Feature 4 - MCP Integration */}
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div className="lg:order-2">
              <h3 className="text-3xl font-bold text-foreground mb-6">
                Integrate tools and data with MCP
              </h3>
              <p className="text-lg text-muted-foreground leading-relaxed mb-6">
                Connect to docs, databases, APIs, and more with <a href="#" className="text-primary hover:text-primary/80 underline">native MCP integration</a> so you can bring your world where you work.
              </p>
            </div>
            <div className="lg:order-1 relative">
              <div className="bg-gradient-primary p-1 rounded-2xl">
                <img 
                  src={mcpImage} 
                  alt="Kiro IDE displays MCP server settings with git and fetch commands"
                  className="w-full rounded-2xl"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default DetailedFeatures;