// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkgnvehniiuuhffqmkdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrZ252ZWhuaWl1dWhmZnFta2RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODA2NDUsImV4cCI6MjA2ODk1NjY0NX0.fQ8fZ7mZSJ8DaQrDgwTRgVsnCo-PkxPm2SCF1HdQZ_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});